<?php

/** @var \Local\Blog\Block\Template $block */
$blogs = $block->updateTestName();
// var_dump($blogs);
// die();
?>

<!-- <div class="template">
   <h1>Templates</h1>
</div> -->
<?php foreach ($blogs as $blog) : ?>
   <h1><?= $block->escapeHtml($blog->getData('title')) ?><span>
         <a href="<?= $block->getUrl('*/*/delete',['id' => $blog->getId()]) ?>">Delete</a>
      </span></h1>
   <p><?= $block->escapeHtml($blog->getData('description')) ?></p>
<?php endforeach; ?>
<form class="form" id="my-form" method="post" action="<?php echo $block->getFormActionUrl() ?>" data-mage-init='{"validation":{}}'>
   <fieldset class="fieldset">
      <div class="field required">
         <label class="label" for="title"><span><?php echo __('Title') ?></span></label>
         <div class="control">
            <input name="title" id="title" title="<?php echo __('Title') ?>" class="input-text" type="text" data-validate="{required:true}">
         </div>
      </div>
      <div class="field required">
         <label class="label" for="description"><span><?php echo __('Description') ?></span></label>
         <div class="control">
            <input name="description" id="description" title="<?php echo __('Description') ?>" class="input-text" type="text" data-validate="{required:true}">
         </div>
      </div>
      <div class="actions-toolbar">
         <div class="primary">
            <button type="submit" value="Submit" class="action submit primary" title="<?php echo __('Submit') ?>">
               <span><?php echo __('Submit') ?></span>
            </button>
         </div>
      </div>
   </fieldset>
</form>